### ISSUE TITLE
Python error in GetStatsFunc

### ISSUE THREAD

**Issue by chrisjeter** [ZertoPublic/zroc#6]
Exception in thread Thread-828 (GetStatsFunc):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/python-node-exporter.py", line 207, in GetStatsFunc
    CurrentEncryptedLBs               = abs(vm['EncryptionStatistics']['EncryptedDataInLBs'] - oldvmdata[0]['EncryptionStatistics']['EncryptedDataInLBs'])
                                            ~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'EncryptionStatistics'

**Comment by recklessop** [comment]
My guess is that this has to do with zroc running against a zvma 10.0 appliance. I have a 10.0 compatible branch of the zexporter completed. Just qa testing it at the moment before i publish the docker image.
